#!/bin/bash

# Build Z3 if needed
make z3/build/com.microsoft.z3.jar

# Create temp directory. See below
mkdir -p temp

# On my machine, /tmp is mounted noexec, so I can't execute code from there.
# SBT copies libraries to a temp directory before executing, so setting
# java.io.tmpdir makes sure it uses a tempdir that it can execute from
# We also have to set LD_LIBRARY_PATH to indicate where the Z3 libraries are
LD_LIBRARY_PATH=z3/build  sbt -Djava.io.tmpdir=temp "$@"
